### ISSUE TITLE
Possible test infrastructure problem

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/fletch#109]
In the middle of a `test.py` run on the buildbot, it aborted due to:
```
Unhandled exception:
Uncaught Error: VM exited before print an address on stdout
Stack Trace:
#0      FletchVm.start.<start_async_body> (file:///b/build/slave/target-fletch-linux-release-arm/build/fletch/pkg/fletchc/lib/fletch_vm.dart)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:14)
#2      _RootZone.runBinary (dart:async/zone.dart:1171)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:580)
#5      _Future._completeError (dart:async/future_impl.dart:376)
#6      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:431)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#8      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

See https://uberchromegw.corp.google.com/i/client.dart.internal/builders/target-fletch-linux-release-arm/builds/323/steps/Test%20ReleaseXARM/logs/stdio

cc @peter-ahe-google

**Comment by peter-ahe-google** [comment]
This is probably caused by a very early crash in the Fletch VM. Regardless, it shouldn't crash test.dart.
