### ISSUE TITLE
Killing the fletch binary while a program is compiling will make fletch show log crash

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#198]
cc @peter-ahe-google @wibling 

Version: 0.1.0-dev.5.0
OS: Linux

How to reproduce the issue:
```
while [ $? -eq 0 ]; do bin/fletch run samples/general/hello.dart ; done
```
kill the loop with ctrl-c

Run
```
bin/fletch show log
```

Expected ouput: The log

Actual output (this seems to happen if we kill it while the compiler is running, so if you don't hit that try again):
```
bin/fletch show log
The Fletch program is broken and has crashed.

The Fletch team would greatly appreciate if you would take a moment to
report this problem at https://github.com/dart-lang/fletch/issues/new

Please include the following information:

* the name and version of your operating system

* the Fletch SDK version (0.1.0-dev.5.0)

* the entire message you see here (including the full stack trace below)

The null object does not have a method 'onData'.

NoSuchMethodError: method not found: 'onData'
Receiver: null
Arguments: [Closure: (dynamic) => dynamic]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      IsolateController.attachClient.<attachClient_async_body> (package:fletchc/src/driver/driver_main.dart:513:23)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:900)
#5      _CustomZone.run (dart:async/zone.dart:803)
#6      _CustomZone.runGuarded (dart:async/zone.dart:709)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#8      _rootRun (dart:async/zone.dart:904)
#9      _CustomZone.run (dart:async/zone.dart:803)
#10     _CustomZone.runGuarded (dart:async/zone.dart:709)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#13     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 1371153006](https://codereview.chromium.org/1371153006/)
