### ISSUE TITLE
Debugger hangs on hello.dart

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#218]
Repro steps:

1. Attach a R Pi 2 and make sure you can run: ```fletch run ./fletch-sdk/samples/general/hello.dart in session remote``` and get ```Hello from Linux running on raspberrypi.```

2. Start the debugger in the remote session: ```fletch debug ./fletch-sdk/samples/general/hello.dart in session remote```

3. Invoke the l or p command

=> Debugger hangs

**Comment by mit-mit** [comment]
If you kill the session with CTRL-C you get:

```
^Ctype 'ConnectionError' is not a subtype of type 'ProcessBacktrace' of 'backtraceResponse'.
#0      Session.getStackTrace.<getStackTrace_async_body> (package:fletchc/session.dart)
#1      _rootRunUnary (dart:async/zone.dart:911)
#2      _CustomZone.runUnary (dart:async/zone.dart:811)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#5      _Future._completeWithValue (dart:async/future_impl.dart:368)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#7      _rootRun (dart:async/zone.dart:904)
#8      _CustomZone.run (dart:async/zone.dart:803)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#11     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#12     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
