### ISSUE TITLE
Stack trace printing fails when no frame is "visible"

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/fletch#241]
```
$ ./out/DebugIA32Clang/fletch run out/DebugIA32Clang/generated_tests/language/class_syntax_test_01.dart
out/DebugIA32Clang/generated_tests/language/class_syntax_test_01.dart:10:23:
Error: Can't find '}' to match '{'.
class ClassSyntaxTest {
                      ^
out/DebugIA32Clang/generated_tests/language/class_syntax_test_01.dart:10:23:
Error: Can't find '}' to match '{'.
class ClassSyntaxTest {
                      ^
Compile error
RangeError (index): Invalid value: Not in range 0..4, inclusive: -1
#0      List.[] (dart:core-patch/array.dart:11)
#1      StackTrace.visibleFrame (package:fletchc/stack_trace.dart:160:23)
#2      StackTrace.list (package:fletchc/stack_trace.dart:168:12)
#3      DebugState.list (package:fletchc/debug_state.dart:135:30)
#4      Session.list.<list_async_body> (package:fletchc/session.dart:551:23)
#5      _rootRunUnary (dart:async/zone.dart:911)
#6      _CustomZone.runUnary (dart:async/zone.dart:811)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#9      _Future._completeWithValue (dart:async/future_impl.dart:368)
#10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#11     _rootRun (dart:async/zone.dart:904)
#12     _CustomZone.run (dart:async/zone.dart:803)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#15     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by peter-ahe-google** [comment]
I've assigned @wibling, but perhaps @madsager is interested in this.
