### ISSUE TITLE
Hello world fails on install from latest SDK build

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#313]
```
lukechurch-macbookpro:fletch-sdk lukechurch$ fletch run samples/general/hello.dart 
The Fletch program is broken and has crashed.

The Fletch team would greatly appreciate if you would take a moment to
report this problem at https://github.com/dart-lang/fletch/issues/new

Please include the following information:

* the name and version of your operating system

* the Fletch SDK version (0.2.0-dev.3.0)

* the entire message you see here (including the full stack trace below)

IsolateSpawnException: Unhandled exception:
Packages file 'file:///Users/lukechurch/Downloads/fletch-sdk/internal/pkg/fletchc/.packages' not found.
#0      _handlePackagesReply (dart:_builtin:416)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:358)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:285)
#2      IsolatePool.spawnIsolate.<spawnIsolate_async_body> (package:fletchc/src/driver/driver_main.dart:710:37)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:900)
#5      _CustomZone.run (dart:async/zone.dart:803)
#6      _CustomZone.runGuarded (dart:async/zone.dart:709)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#8      _rootRun (dart:async/zone.dart:904)
#9      _CustomZone.run (dart:async/zone.dart:803)
#10     _CustomZone.runGuarded (dart:async/zone.dart:709)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#13     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by lukechurch** [comment]
``` fletch --version
0.2.0-dev.3.0
```

**Comment by lukechurch** [comment]
fletch quit
and repeat the command succeeded.

So this is a case of needing a better error message.
