### ISSUE TITLE
Incremental compilation crashes on adding a new method

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/fletch#322]
```
class Foo {
  void newInt() {
    var theAnswer = 4445;

    print("The answer is $theAnswer");
    throw "Well, that was wrong";
  }

}

main() {
  print ("Startup");
  var f = new Foo();
  f.newInt();
}
```

to 

```
class Foo {
  void newInt() {
    var theAnswer = 4445;

    another();

    print("The answer is $theAnswer");
    throw "Well, that was wrong";
  }

  void another() {
    var theAnswer = -20;
    print("Another answer is $theAnswer");

  }
}

main() {
  print ("Startup");
  var f = new Foo();
  f.newInt();
}
```

lukechurch-macbookpro:fletch lukechurch$ ./update.sh target.dart 

```
../../src/vm/session.cc:1000: error: expected: !program()->is_compact()
The Fletch program is broken and has crashed.

The Fletch team would greatly appreciate if you would take a moment to
report this problem at https://github.com/dart-lang/fletch/issues/new

Please include the following information:

* the name and version of your operating system

* the Fletch SDK version (0.2.0-edge.fc167593c0abeba13cc65c89042e8ad57bdde0b2)

* the entire message you see here (including the full stack trace below)

Uncaught Error: Bad state: Trying to send command CommandCode.ProcessRestartFrame(0) to fletch-vm, but the connection is already closed.
Stack Trace:
#0      FletchVmSession.sendCommand.<sendCommand_async_body> (package:fletchc/session.dart:133:7)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#2      _rootRun (dart:async/zone.dart:904)
#3      _CustomZone.run (dart:async/zone.dart:803)
#4      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#6      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Session 'Live' was terminated.
```

update.sh does:

```
TARGET=$1
./out/DebugIA32Clang/fletch compile $TARGET in session Live
./out/DebugIA32Clang/fletch debug apply in session Live
./out/DebugIA32Clang/fletch debug restart in session Live
```

**Comment by peter-ahe-google** [comment]
I think the problem is that you added an instance method. Try changing `update.sh` to this:

```bash
set -e
TARGET=$1
./out/DebugIA32Clang/fletch compile --fatal-incremental-failures $TARGET in session Live
./out/DebugIA32Clang/fletch debug apply in session Live
./out/DebugIA32Clang/fletch debug restart in session Live
```
