### ISSUE TITLE
The flash-sd-card script fails with a long stacktrace if downloading the image fails

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#324]
This is from using a local HTTP server which closes the connection before all bytes was sent.

```
$ platforms/raspberry-pi2/flash-sd-card --version 0.2.0-dev.4.5 --image-url http://127.0.0.1:57866 --sd-card=/dev/xxx
This program requires superuser to run.
This program will prepare an SD card for Fletch on the Raspberry Pi 2.

Using the SD card /dev/xxx.

This will delete all contents on the card. Press Enter to use this card (Ctrl-C to cancel).
Enter the name of the device - default is 'fletch' (press Enter to accept): 
Enter the static IP address you would like the device to have. Leave it blank to have it assigned via DHCP: 
Downloading SD card image.
Downloading: received 0 Mb of 0 MbUnhandled exception:
Uncaught Error: HttpException: Connection closed while receiving data, uri = http://127.0.0.1:57866
Stack Trace:
#0      PlatformService.downloadWithProgress.<downloadWithProgress_async_body> (file:///usr/local/prj/dart/github/fletch/fletch/pkg/flash_sd_card/lib/src/platform_service.dart)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:14)
#2      _RootZone.runBinary (dart:async/zone.dart:1171)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:580)
#5      _Future._completeError (dart:async/future_impl.dart:376)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#7      _Completer.completeError (dart:async/future_impl.dart:27)
#8      _FileStreamConsumer.addStream.<anonymous closure>.error (dart:io/file_impl.dart:192)
#9      _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:371)
#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#13     _SinkTransformerStreamSubscription._addError (dart:async/stream_transformers.dart:81)
#14     _EventSinkWrapper.addError (dart:async/stream_transformers.dart:16)
#15     _StreamHandlerTransformer._defaultHandleError (dart:async/stream_transformers.dart:253)
#16     _HandlerEventSink.addError (dart:async/stream_transformers.dart:218)
#17     _SinkTransformerStreamSubscription._handleError (dart:async/stream_transformers.dart:127)
#18     _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#19     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#20     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#21     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#22     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:145)
#23     _addErrorWithReplacement (dart:async/stream_pipe.dart:196)
#24     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:299)
#25     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:176)
#26     _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#27     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#28     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#29     _DelayedError.perform (dart:async/stream_impl.dart:606)
#30     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#31     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#33     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sgjesse** [comment]
This is from a real error:

```
Downloading: received 145560512 of 1354235743Unhandled exception:
Uncaught Error: HttpException: Connection closed while receiving data, uri = https://storage.googleapis.com/fletch-archive/channels/dev/raw/0.2.0-dev.4.5/sdk/fletch_raspbian.img.zip
Stack Trace:
#0      PlatformService.downloadWithProgress.<downloadWithProgress_async_body> (file:///Users/bak/fletch-sdk/internal/pkg/flash_sd_card/lib/src/platform_service.dart)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:14)
#2      _RootZone.runBinary (dart:async/zone.dart:1171)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:580)
#5      _Future._completeError (dart:async/future_impl.dart:376)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#7      _Completer.completeError (dart:async/future_impl.dart:27)
#8      _FileStreamConsumer.addStream.<anonymous closure>.error (dart:io/file_impl.dart:192)
#9      _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:371)
#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#13     _SinkTransformerStreamSubscription._addError (dart:async/stream_transformers.dart:81)
#14     _EventSinkWrapper.addError (dart:async/stream_transformers.dart:16)
#15     _StreamHandlerTransformer._defaultHandleError (dart:async/stream_transformers.dart:253)
#16     _HandlerEventSink.addError (dart:async/stream_transformers.dart:218)
#17     _SinkTransformerStreamSubscription._handleError (dart:async/stream_transformers.dart:127)
#18     _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#19     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#20     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#21     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#22     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:145)
#23     _addErrorWithReplacement (dart:async/stream_pipe.dart:196)
#24     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:299)
#25     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:176)
#26     _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#27     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#28     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#29     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#30     _StreamController&&_SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:740)
#31     _StreamController._addError (dart:async/stream_controller.dart:616)
#32     _StreamController.addError (dart:async/stream_controller.dart:568)
#33     _HttpParser._onDone (dart:io/http_parser.dart:831)
#34     _RootZone.runGuarded (dart:async/zone.dart:1093)
#35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#37     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#38     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:744)
#39     _StreamController._closeUnchecked (dart:async/stream_controller.dart:597)
#40     _StreamController.close (dart:async/stream_controller.dart:590)
#41     _Socket._onError (dart:io-patch/socket_patch.dart:1847)
#42     _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#43     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#44     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:371)
#45     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#46     _StreamController&&_SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:740)
#47     _StreamController._addError (dart:async/stream_controller.dart:616)
#48     _StreamController.addError (dart:async/stream_controller.dart:568)
#49     _RawSecureSocket._reportError (dart:io/secure_socket.dart:942)
#50     _RawSecureSocket._pushAllFilterStages.<anonymous closure> (dart:io/secure_socket.dart:1173)
#51     _RootZone.runUnary (dart:async/zone.dart:1166)
#52     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#53     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#54     _Future._completeWithValue (dart:async/future_impl.dart:368)
#55     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#57     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

/cc @larsbak

**Comment by sgjesse** [comment]
Fixed in https://github.com/dart-lang/fletch/commit/605c022e7865efeb11dae5b789ad6506a4ff312e.
