### ISSUE TITLE
Crash in platforms/raspberry-pi2/flash-sd-card tool

### ISSUE THREAD

**Issue by kasperl** [dart-lang/fletch#339]
Second time I ran the tool, I got this exception. Don't know if it could be related to my machine entering some sort of power-save mode, but I did have to unlock the screen as I returned to the Macbook.

```
...
Writing image to SD card.
Writing: DONE                                                                
Running sync
Mounting the SD card.
Unhandled exception:
Uncaught Error: FileSystemException: Directory listing failed, path = '/Volumes/boot/' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      flashCDCard.<flashCDCard_async_body> (file:///Users/kasperl/Fletch/fletch-sdk/internal/pkg/flash_sd_card/lib/flash_sd_card.dart)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:14)
#2      _RootZone.runBinary (dart:async/zone.dart:1171)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:521)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:580)
#5      _Future._completeError (dart:async/future_impl.dart:376)
#6      _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:371)
#9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#10     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:145)
#11     _ForwardingStream._handleError (dart:async/stream_pipe.dart:108)
#12     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:176)
#13     _RootZone.runBinaryGuarded (dart:async/zone.dart:1115)
#14     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#15     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#16     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#17     _StreamController&&_SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:740)
#18     _StreamController._addError (dart:async/stream_controller.dart:616)
#19     _StreamController.addError (dart:async/stream_controller.dart:568)
#20     _AsyncDirectoryLister.error (dart:io/directory_impl.dart:384)
#21     _AsyncDirectoryLister.next.<anonymous closure> (dart:io/directory_impl.dart:344)
#22     _RootZone.runUnary (dart:async/zone.dart:1166)
#23     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#24     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#25     _Future._completeWithValue (dart:async/future_impl.dart:368)
#26     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#28     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sgjesse** [comment]
We will have to look more into this. If the Mac goes to sleep while downloading it also does not continue downloading when it wakes up.
