### ISSUE TITLE
fletch run error.dart two times hits an unreachable assertion

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#345]
What will reproduce the issue:
error.dart:
```
void main() {
  foobar;
}
```

Run once and get the expected:
```
out/ReleaseIA32/fletch run test.dart
usr/local/google/home/ricow/src/fletch/fletch/test.dart:2:3:
Warning: Cannot resolve 'foobar'.
  foobar;
  ^^^^^^
Uncaught exception: Instance of 'NoSuchMethodError' {
...
```

Run a second time:
```
out/ReleaseIA32/fletch run test.dart
file:///usr/local/google/home/ricow/src/fletch/fletch/test.dart+16-22: Cannot resolve 'foobar'.
../../src/vm/program_folder.cc:474: error: unreachable code
Bad state: Trying to send command CommandCode.Debugging() to fletch-vm, but the connection is already closed.
#0      FletchVmSession.sendCommand.<sendCommand_async_body> (package:fletchc/session.dart:138:7)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#2      _rootRun (dart:async/zone.dart:907)
#3      _CustomZone.run (dart:async/zone.dart:802)
#4      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:735)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#6      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by herhut-ggl** [comment]
This is a duplictate of issue #355.
