### ISSUE TITLE
Running 'fletch debug' after 'fletch run crashing.dart' crashes

### ISSUE THREAD

**Issue by wibling** [dart-lang/fletch#386]
If running 'fletch debug' after running 'fletch run crashing.dart' where crashing.dart fails with an uncaught exception you get the below backtrace:

wibling /work/fletch-repo/fletch (master) $ ./out/DebugIA32/fletch debug
../../src/vm/session.cc:1025: error: expected: !program()->is_optimized()
The Fletch program is broken and has crashed.

The Fletch team would greatly appreciate if you would take a moment to
report this problem at https://github.com/dart-lang/fletch/issues/new

Please include the following information:

* the name and version of your operating system

* the Fletch SDK version (0.2.0-edge.2cdfd792ffe62d0dda3da62ae226324c07199327)

* the entire message you see here (including the full stack trace below)

Bad state: Trying to send command VmCommandCode.PushFromMap(MapId.methods, 11) to fletch-vm, but the connection is already closed.
#0      FletchVmSession.sendCommand.<sendCommand_async_body> (package:fletchc/vm_session.dart:137:7)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#2      _rootRun (dart:async/zone.dart:907)
#3      _CustomZone.run (dart:async/zone.dart:802)
#4      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:735)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#6      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Session 'local' was terminated.

**Comment by wibling** [comment]
Running this in 'session remote' on a RPI2 works. It seems to only happen when running locally.
