### ISSUE TITLE
Crash in vm when passing double to Uint8List constructor

### ISSUE THREAD

**Issue by ricowind** [dart-lang/fletch#392]
How to reproduce the problem
Apply:
```
diff --git a/tests/pkg/socket/socket_test.dart b/tests/pkg/socket/socket_test.dart
index dd67f30..2ad5a45 100644
--- a/tests/pkg/socket/socket_test.dart
+++ b/tests/pkg/socket/socket_test.dart
@@ -66,7 +66,7 @@ void validateBuffer(buffer, int length) {
 }
 
 const CHUNK_SIZE = 256;
-const SMALL_READ_BUFFER = CHUNK_SIZE ~/ 8;
+const SMALL_READ_BUFFER = CHUNK_SIZE / 8;
 
 
 void testReadWrite() {
```

Run:
```
tools/test.py -mdebug pkg/socket
```

The vm will crash with (from gdb):
```
../../src/vm/object.h:2101: error: expected: object->IsLargeInteger()

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xf6affb40 (LWP 5475)]
0xf7fdb440 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fdb440 in __kernel_vsyscall ()
#1  0xf7cbd607 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7cc0a33 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x080a1b8f in fletch::Platform::ImmediateAbort () at ../../src/shared/platform_posix.cc:163
#4  0x0809fe31 in fletch::DynamicAssertionHelper::Fail<fletch::DynamicAssertionHelper::ASSERT> (
    file=file@entry=0x80aa9c8 "../../src/vm/object.h", line=line@entry=2101, format=format@entry=0x80aa958 "expected: %s")
    at ../../src/shared/assert.cc:37
#5  0x080521b0 in cast (object=0x80db809) at ../../src/vm/object.h:2101
#6  AsForeignWord (object=0x80db809) at ../../src/vm/heap.h:189
#7  fletch::Native_ForeignAllocate (process=0x80d44d0, arguments=...) at ../../src/vm/ffi.cc:16
#8  0x0804dbf4 in BC_InvokeNative () at obj/src/vm/fletch_vm_library.gen/generated.S:1613
#9  0x080d44d0 in ?? ()
```

**Comment by ricowind** [comment]
This is actually a problem with Uint8List, small repro:
```
import 'dart:typed_data';

void main() {
  var x = 32.0;

  var bytes = new Uint8List(x);
}
```
