### ISSUE TITLE
Flaky compiler crash in language/mixin_illegal_superclass_test/14

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/fletch#77]
When running the tests locally, the above test was crashing. Rerunning the test worked fine.

```
FAILED: none-fletchc debug_ia32 language/mixin_illegal_superclass_test/14
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[vm]:

stdout:
out/DebugIA32/generated_tests/language/mixin_illegal_superclass_test_14.dart:12:1:
Error: Class used as mixin must have Object as superclass.
class M2 extends M0 { }
^^^^^
out/DebugIA32/generated_tests/language/mixin_illegal_superclass_test_14.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

'package:compiler/src/universe/universe.dart': Failed assertion: line 661 pos 12: 'kind == SelectorKind.OPERATOR ||
           kind == SelectorKind.INDEX ||
           !Elements.isOperatorName(memberName.text) ||
           identical(memberName.text, '??')' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      Selector.Selector.internal (package:compiler/src/universe/universe.dart:661:12)
#2      Selector.Selector (package:compiler/src/universe/universe.dart:690:27)
#3      Selector.Selector.getter (package:compiler/src/universe/universe.dart:738:14)
#4      FletchBackend.createTearoffGetterForFunction (package:fletchc/src/fletch_backend.dart:1073:13)
#5      FletchBackend.createTearoffStubs.<anonymous closure> (package:fletchc/src/fletch_backend.dart:1050:9)
#6      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#7      Universe.forEachInvokedGetter (package:compiler/src/universe/universe.dart:291:21)
#8      FletchBackend.createTearoffStubs (package:fletchc/src/fletch_backend.dart:1048:29)
#9      FletchBackend.assembleProgram (package:fletchc/src/fletch_backend.dart:1080:5)
#10     Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:1677:31)
#11     Compiler.runCompiler.<anonymous closure> (package:compiler/src/compiler.dart:1518:7)

...

Short reproduction command (experimental):
    python tools/test.py -rfletchc -t120 language/mixin_illegal_superclass_test/14

```

**Comment by mit-mit** [comment]
Looks like this was fixed
