### ISSUE TITLE
Flakiness running fletch_tests

### ISSUE THREAD

**Issue by madsager** [dart-lang/fletch#90]
Locally, I see occasional errors when running:

    ./tools/test.py -mrelease fletch_tests

It looks like we get a mix of printing of bytecodes and JSON protocol messages:

```
Unhandled exception:
Uncaught Error: FormatException: Unexpected character (at character 298)
...local 10, invoke 91392, load local{"type":"TestStdoutLine","name":"incre...
                                       ^

Stack Trace:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1326)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:850)
#2      _parseJson (dart:convert-patch/convert_patch.dart:19)
#3      JsonDecoder.convert (dart:convert/json.dart:496)
#4      JsonCodec.decode (dart:convert/json.dart:124)
#5      Message.Message.fromJson (file:///usr/local/google/home/ager/ssd/fletch-repo/fletch/tests/fletch_tests/messages.dart:28:38)
#6      messageTransformer.<anonymous closure> (file:///usr/local/google/home/ager/ssd/fletch-repo/fletch/tests/fletch_tests/messages.dart:20:19)
#7      _HandlerEventSink.add (dart:async/stream_transformers.dart:216)
#8      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#12     _LineSplitterSink._addSlice (dart:convert/line_splitter.dart:76)
#13     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:48)
#14     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#15     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#16     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#23     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#24     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#25     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#31     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:695)
#32     _StreamController._add (dart:async/stream_controller.dart:567)
#33     _StreamController.add (dart:async/stream_controller.dart:513)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:1817)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#38     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:695)
#39     _StreamController._add (dart:async/stream_controller.dart:567)
#40     _StreamController.add (dart:async/stream_controller.dart:513)
#41     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1368)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:747)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#44     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by madsager** [comment]
Looks like this is only happening with my change to use a full session for verbs. I'll look into that.
